### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by agus4402** [carson-katri/dream-textures#691]
### Description

Hi, im getting this error with a gtx 1660. I hear that NVIDEA 16 series graphic cards are having some problems with stable diffusion.
It have 6 vram, thats over the recomended so this shouldn't be happening.

This is the error
![image](https://github.com/carson-katri/dream-textures/assets/83419633/830b5ff3-0e21-4142-81a1-da0f2eff660d)

Is any way to set a similar configuration like this? 

"--xformers --upcast-sampling --precision full --medvram --no-half-vae"

Hope theres a solution v:

Thanks!

### Steps to Reproduce

Generate a texture at half precision

### Expected Behavior

Generate a texture

### Addon Version

Windows (CUDA)

### GPU

NVIDIA 16 Series

**Comment by mercouriu** [comment]
Hi. I have this too (1660ti) with cuda. I have this error both in stable-diffustion-2.1 and stable-diffusion-2-depth. Anybody knows how to fix that?:

RuntimeError("OutOfMemoryError('CUDA out of memory. Tried to allocate 90.00 MiB (GPU 0; 6.00 GiB total capacity; 5.14 GiB already allocated; 0 bytes free; 5.24 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF')")

**Comment by agus4402** [comment]
> Hi. I have this too (1660ti) with cuda. I have this error both in stable-diffustion-2.1 and stable-diffusion-2-depth. Anybody knows how to fix that?:
> 
> RuntimeError("OutOfMemoryError('CUDA out of memory. Tried to allocate 90.00 MiB (GPU 0; 6.00 GiB total capacity; 5.14 GiB already allocated; 0 bytes free; 5.24 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF')")

I
 I solved this problem by changing the CPU offload to Model
![image](https://github.com/carson-katri/dream-textures/assets/83419633/ae8dea6e-fc51-41c0-bfd0-e6b448b34b08)

**Comment by badde-media** [comment]
I have this error, too, on a 3070ti with 8GB RAM.

**Comment by ddxl123** [comment]
An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

RuntimeError("OutOfMemoryError('CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 4.00 GiB total capacity; 3.40 GiB already allocated; 0 bytes free; 3.46 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF')")
